---
- hosts: jenkinsvm
  become: yes
  remote_user: ergi
  become_user: root
  tasks:

  - name: Copy jenkins.repo
    copy:
      src: jenkins.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: '0644'

  - name: Import jenkins key from url
    command: /bin/rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

  - name: yum update
    yum:
      name: '*'
      state: latest
   
  - name: Install epel release
    yum:
      name: epel-release
      state: present

  - name: Install java
    yum:
      name: java-11-openjdk-devel
      state: present

  - name: Install jenkins
    yum:
      name: jenkins
      state: latest

  - name: daemon-reload to pick up config changes
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Start jenkins
    ansible.builtin.systemd:
      name: jenkins
      state: started
  
  - name: Get password fot admin jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: result

  - debug: 
      var: result
      verbosity: 2