---
- hosts: terraformvm
  become: yes
  tasks:
    - name: update_cache
      apt:
        update_cache: yes
    - name: install Dependencies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg-agent
    - name: install python
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - python3
        - python3-pip
    - name: Install Docker python module
      pip:
        name: docker
        state: latest
    - name: Add an apt signing key for Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add repository for stable Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Add user to docker group
      user:
        name: ergi
        group: docker
    # Clone Repositories
    - name: Clone github repository quiz-backend-update
      git:
        repo: https://github.com/Kontetsu/quiz-backend-update.git
        dest: /home/ergi/quiz-backend-update
        clone: yes
        update: yes
    # Clone Repositories
    - name: Clone github repository quiz-frontend-update
      git:
        repo: https://github.com/Kontetsu/quiz-frontend-update.git
        dest: /home/ergi/quiz-frontend-update
        clone: yes
        update: yes
    # Build backend image with shell command    
    - name: build backend image
      docker_image:
        name: backend
        tag: v01
        build:
          path: /home/ergi/quiz-backend-update/
        source: build
        state: present 
    - name: build frontend image
      docker_image:
        name: frontend
        tag: v01
        build:
          path: /home/ergi/quiz-frontend-update/
        source: build
        state: present
    # Create backend container
    - name: Create a network
      docker_network:
        name: quiz
    - name: Create backend container
      docker_container:
        name: backend
        hostname: backend
        networks:
          - name: quiz
        image: backend:v01
        state: started
        recreate: yes
        published_ports: 8080:8080
    # Create Frontend container
    - name: Create frontend container
      docker_container:
        name: frontend
        hostname: frontend
        networks:
          - name: quiz
        image: frontend:v01
        state: started
        recreate: yes
        published_ports: 80:80
